### ISSUE TITLE
Bad Key hash

### ISSUE THREAD

**Issue by Klauserus** [shchmue/Lockpick_RCM#1]
Hi

I used rcm payload. I have sept folder with the nessesary files. But, when i load Tinfoil (blawar) it comes to this message: Bad key hash: master key 07.

the prod.key is renamed into txt file in the tinfoil folder.

I hope you can help.

Thanks for your work

**Comment by shchmue** [comment]
You're on 7.0? How many keys did Lockpick_RCM dump? Should be 126.

In the meantime, since we can't share keys, how about this. Open your key file in the text editor, copy the key master_key_07 into the 'binary hash' box here: https://www.fileformat.info/tool/hash.htm click Hash and copy and paste what's in the SHA-256 section here.

**Comment by shchmue** [comment]
I found out this is a Tinfoil problem and there will be a fix for it soon
