### ISSUE TITLE
SD seed dump?

### ISSUE THREAD

**Issue by Skirmisher** [shchmue/Lockpick_RCM#13]
I may be misunderstanding something, but I don't see a value that looks like the SD seed in a full prod.keys dump. [The Lockpick Horizon applet](https://github.com/shchmue/Lockpick) states it dumps the SD seed, but it seems like the RCM version supersedes that one in every other way, and I'd rather not run CFW on the particular Switch I'm interested in if I can help it. (The amount of outdated info on how to extract keys in general is not helping with my confusion...)

Is this not possible with the bare-metal application, or is it simply not implemented yet?

**Comment by shchmue** [comment]
https://github.com/shchmue/Lockpick_RCM/blob/master/source/keys/keys.c#L655-L684 it's dumped here. There's messaging if it can't be found. If FS keys can't be found (they're needed to decrypt the System partition) or it otherwise fails to mount NAND, it can't be dumped. It also requires an SD inserted that has been booted to the Switch OS before, or else you must copy the `sd:/Nintendo/Contents/private` file to the SD that's inserted when Lockpick_RCM runs.

What kind of messaging did you get when you ran the program?
