### ISSUE TITLE
Missing Keys?

### ISSUE THREAD

**Issue by Buzbee** [shchmue/Lockpick_RCM#2]
Lockpick has 121 keys on 7.01
Lockpick_RCM has 126 keys. on 7.01. It adds 7 keys but removes 2 keys. They are master_kek_06 & tsec_root_key. Is this a bug or by design?

**Comment by shchmue** [comment]
It's by design, the only version where public hax exist to get tsec_root_key is 6.2.0. Once Nintendo fixes/moves on from TSEC/releases a new hardware rev and renders this cat and mouse game moot, SciresM has said he and hexkyz would release TSEC hax, then we will know all the keys. Until then, only on 6.2.0 where SMMU hax works.
