### ISSUE TITLE
How to obtain keys using Lockpick RCM on Mariko 

### ISSUE THREAD

**Issue by Ericvf** [shchmue/Lockpick_RCM#59]
Hi.

My Mariko V2 switch with SXCore is using SXGear to boot into Hekate. It's using HOS 10.0.2 for the Sysnand and HOS 12.0.3 for Emunand. 

When running the Lockpick_RCM payload via Hekate it gives the choice of Sysnand and Emunand. Either choices result in partialaes.keys and prod.keys files written to the sd:\switch folder. 

When inspecting the partialaes.keys file it shows 4 identical numbers for the 12 slot:
For example:
```
12
2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d
2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d
2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d
2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d
```

So I've ran the PartialAesKeyCrack batch file with the 4 identical keys:

`PartialAesKeyCrack.exe --numthreads=16 2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d 2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d 2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d 2xyzxyzxyzxyzxyzxyzxyzxyzxyz123d >nul`

When it is done running the output is:

```
[15:10:46:888272] T[12408]: Thread 15 affinity set to 0x8000 (was 0x8000)
[15:10:46:888273] T[12376]: Thread 14 affinity set to 0x4000 (was 0xffff)
PartialAesKeyCrack.exe v0.2 built on 10/04/2018 10:45 CET by rajkosto
Press any key to continue . . .
``` 

So what am I missing? Is this working as intended? I was expecting some output from PartialAesKeyCrack but I don't see anything meaningful. Should the 4 keys be identical? 

What information should I be expecting to backup (for future recovery)?  

Thanks for the help and information

**Comment by Masamune3210** [comment]
Could it have something to do with the fact that you are piping stdout to null? Not familiar with the program as I have a RCM unit

**Comment by shchmue** [comment]
all 4 partials being the same suggests something is goofy about what chainloaded lockpick_rcm. you might need to use starcraft instead. honestly i don't really understand how mariko boot memes work, but the partials must be different to get a legit result.

note though that this only has extremely niche use, like for example reversing the kernel or security monitor. they're not otherwise super handy keys for anything that lockpick_rcm or any pc tools can do

**Comment by shchmue** [comment]
try new version, reopen if needed
